services:
  db:
    image: pgvector/pgvector:pg16
    container_name: exmeralda-db
    environment:
      POSTGRES_DB: exmeralda_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 2 &&
        ollama pull llama3.2:latest &&
        ollama pull unclemusclez/jina-embeddings-v2-base-code &&
        wait
      "
    # If you have a GPU and want to use it, uncomment the next line:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  db_data:
  ollama_data: