@startuml model

title "Exmeralda Model"

set namespaceSeparator none
hide circle
hide methods

' skinparam linetype ortho
skinparam defaultFontName Roboto Mono
skinparam shadowing false

package LLM {
  object Provider {
    id: string
    type: enum(ollama, openai, mock)
    config: jsonb
    name: string
  }

  object ModelConfig {
    id: string
    name: string
    config: jsonb
  }

  object ModelConfigProvider {
    id: string
    name: string
  }

  object SystemPrompt {
    id: string
    prompt: string
  }

  object PromptTemplate {
    id: string
    template: string
  }

  ModelConfigProvider "n" -l- "1" Provider
  ModelConfigProvider "n" -d- "1" ModelConfig
  SystemPrompt "1" -r- "n" ModelConfig
  PromptTemplate "1" -u- "n" ModelConfig
}

package Chats {
  object Session {
    id: string
    title: string
  }

  object Message {
    id: string
    role: enum (user, assitant)
    index: integer
    content: string
    incomplete: boolean
  }

  object Reaction {
    id: string
    type: enum (upvote, downvote)
  }

  object Source {
    id: string
  }

  Message "1" -d- "0,1" Reaction
  Message "n" -r- "1" Session
  Source "n" -u- "1" Message
}

package Topics {
  object Library {
    id: string
    name: string
    version: string
  }

  object Ingestion {
    id: string
    state: enum (queued, embedding, failed, ready)
    active: boolean
  }

  object Chunk {
    id: string
    type: enum (code, docs)
    source: string
    content: string
    embedding: pgvector
  }

  Library "1" -d- "n" Ingestion
  Chunk "n" -u- "1" Ingestion
}

Message "n" -l- "1" ModelConfig
Session "n" -- "1" Ingestion
Source "n" -- "1" Chunk


@enduml
