
name: Fly Postgres
on:
  push:
    paths:
      - 'Dockerfile.pgvector'

jobs:
  pgvector:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up flyctl'
        uses: superfly/flyctl-actions/setup-flyctl@v1.4

      - name: 'Log in to the registry'
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.pgvector
          tags: registry.fly.io/exmeralda:pgvector
